import { SuggestionRecipe } from './mealSuggestions';

export const recipeCatalog: SuggestionRecipe[] = [
  {
    id: '1',
    name: 'Grilled Chicken Salad',
    image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&h=300&fit=crop',
    calories: 350,
    protein: 35,
    carbs: 20,
    fat: 15,
    prepTime: '20 min',
    difficulty: 'Easy',
    tags: ['High Protein', 'Low Carb', 'Gluten Free'],
    suitableFor: ['weight-loss', 'muscle-gain'],
    ingredients: ['200g chicken breast', 'Mixed greens', 'Cherry tomatoes', 'Cucumber', 'Olive oil', 'Lemon juice'],
    instructions: ['Season and grill chicken breast', 'Chop vegetables', 'Mix greens and vegetables', 'Slice chicken and place on salad', 'Drizzle with olive oil and lemon'],
  },
  {
    id: '2',
    name: 'Quinoa Buddha Bowl',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop',
    calories: 450,
    protein: 18,
    carbs: 65,
    fat: 12,
    prepTime: '30 min',
    difficulty: 'Easy',
    tags: ['Vegetarian', 'High Fiber', 'Balanced'],
    suitableFor: ['maintain', 'general-health'],
    ingredients: ['1 cup quinoa', 'Roasted sweet potato', 'Chickpeas', 'Avocado', 'Spinach', 'Tahini dressing'],
    instructions: ['Cook quinoa according to package', 'Roast sweet potato and chickpeas', 'Arrange quinoa in bowl', 'Top with vegetables and chickpeas', 'Drizzle with tahini dressing'],
  },
  {
    id: '3',
    name: 'Salmon with Asparagus',
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400&h=300&fit=crop',
    calories: 420,
    protein: 40,
    carbs: 15,
    fat: 22,
    prepTime: '25 min',
    difficulty: 'Medium',
    tags: ['High Protein', 'Omega-3', 'Low Carb'],
    suitableFor: ['weight-loss', 'muscle-gain', 'general-health'],
    ingredients: ['200g salmon fillet', 'Fresh asparagus', 'Garlic', 'Lemon', 'Olive oil', 'Herbs'],
    instructions: ['Preheat oven to 400°F', 'Season salmon with herbs and lemon', 'Toss asparagus with olive oil and garlic', 'Bake for 15-18 minutes', 'Serve immediately'],
  },
  {
    id: '4',
    name: 'Protein Pancakes',
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&h=300&fit=crop',
    calories: 380,
    protein: 30,
    carbs: 45,
    fat: 8,
    prepTime: '15 min',
    difficulty: 'Easy',
    tags: ['High Protein', 'Breakfast', 'Post-Workout'],
    suitableFor: ['muscle-gain', 'general-health'],
    ingredients: ['Protein powder', 'Oats', 'Eggs', 'Banana', 'Cinnamon', 'Berries for topping'],
    instructions: ['Blend all ingredients except berries', 'Heat non-stick pan', 'Pour batter and cook until bubbles form', 'Flip and cook other side', 'Top with berries and serve'],
  },
  {
    id: '5',
    name: 'Vegetable Stir-Fry with Tofu',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&h=300&fit=crop',
    calories: 320,
    protein: 20,
    carbs: 35,
    fat: 12,
    prepTime: '20 min',
    difficulty: 'Easy',
    tags: ['Vegetarian', 'Low Calorie', 'Quick'],
    suitableFor: ['weight-loss', 'general-health'],
    ingredients: ['Firm tofu', 'Mixed vegetables', 'Soy sauce', 'Ginger', 'Garlic', 'Sesame oil'],
    instructions: ['Press and cube tofu', 'Stir-fry tofu until golden', 'Add vegetables and stir-fry', 'Add sauce and seasonings', 'Serve hot'],
  },
  {
    id: '6',
    name: 'Greek Yogurt Parfait',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=300&fit=crop',
    calories: 280,
    protein: 25,
    carbs: 35,
    fat: 6,
    prepTime: '5 min',
    difficulty: 'Easy',
    tags: ['High Protein', 'Breakfast', 'Quick'],
    suitableFor: ['weight-loss', 'muscle-gain', 'general-health'],
    ingredients: ['Greek yogurt', 'Granola', 'Mixed berries', 'Honey', 'Chia seeds'],
    instructions: ['Layer yogurt in a glass', 'Add granola', 'Top with berries', 'Drizzle with honey', 'Sprinkle chia seeds'],
  },
  {
    id: '7',
    name: 'Turkey Avocado Wrap',
    image: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?w=400&h=300&fit=crop',
    calories: 410,
    protein: 33,
    carbs: 32,
    fat: 15,
    prepTime: '12 min',
    difficulty: 'Easy',
    tags: ['Lunch', 'High Protein', 'Quick'],
    suitableFor: ['weight-loss', 'muscle-gain', 'maintain'],
    ingredients: ['Whole wheat wrap', 'Sliced turkey', 'Avocado', 'Spinach', 'Tomato', 'Greek yogurt spread'],
    instructions: ['Spread yogurt base on wrap', 'Layer turkey and vegetables', 'Roll tightly and slice in half'],
  },
  {
    id: '8',
    name: 'Mediterranean Chickpea Bowl',
    image: 'https://images.unsplash.com/photo-1523986371872-9d3ba2e2f642?w=400&h=300&fit=crop',
    calories: 470,
    protein: 19,
    carbs: 62,
    fat: 16,
    prepTime: '18 min',
    difficulty: 'Easy',
    tags: ['Vegetarian', 'Fiber Rich', 'Meal Prep'],
    suitableFor: ['maintain', 'general-health', 'weight-loss'],
    ingredients: ['Chickpeas', 'Cucumber', 'Tomato', 'Feta', 'Olives', 'Brown rice'],
    instructions: ['Warm chickpeas with herbs', 'Prepare chopped vegetables', 'Assemble bowl and drizzle olive oil'],
  },
  {
    id: '9',
    name: 'Lean Beef Rice Plate',
    image: 'https://images.unsplash.com/photo-1604908812595-7d0f3f89fe57?w=400&h=300&fit=crop',
    calories: 530,
    protein: 42,
    carbs: 52,
    fat: 17,
    prepTime: '28 min',
    difficulty: 'Medium',
    tags: ['High Protein', 'Performance', 'Dinner'],
    suitableFor: ['muscle-gain', 'maintain'],
    ingredients: ['Lean beef strips', 'Jasmine rice', 'Broccoli', 'Carrots', 'Garlic'],
    instructions: ['Cook rice until fluffy', 'Sear beef with garlic', 'Steam vegetables and plate together'],
  },
  {
    id: '10',
    name: 'Lentil Tomato Soup',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=400&h=300&fit=crop',
    calories: 330,
    protein: 18,
    carbs: 48,
    fat: 7,
    prepTime: '30 min',
    difficulty: 'Easy',
    tags: ['Vegan', 'Comfort', 'High Fiber'],
    suitableFor: ['weight-loss', 'general-health', 'maintain'],
    ingredients: ['Red lentils', 'Crushed tomatoes', 'Onion', 'Carrot', 'Celery', 'Vegetable stock'],
    instructions: ['Saute onion and celery', 'Add lentils and tomatoes', 'Simmer until lentils are soft and blend lightly'],
  },
  {
    id: '11',
    name: 'Shrimp Quinoa Skillet',
    image: 'https://images.unsplash.com/photo-1563379091339-03246963d51a?w=400&h=300&fit=crop',
    calories: 460,
    protein: 36,
    carbs: 40,
    fat: 16,
    prepTime: '24 min',
    difficulty: 'Medium',
    tags: ['Seafood', 'High Protein', 'One Pan'],
    suitableFor: ['muscle-gain', 'maintain', 'general-health'],
    ingredients: ['Shrimp', 'Quinoa', 'Bell pepper', 'Onion', 'Lime', 'Parsley'],
    instructions: ['Cook quinoa separately', 'Saute shrimp with vegetables', 'Fold in quinoa and finish with lime'],
  },
  {
    id: '12',
    name: 'Oatmeal Apple Crunch Bowl',
    image: 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?w=400&h=300&fit=crop',
    calories: 340,
    protein: 14,
    carbs: 55,
    fat: 9,
    prepTime: '10 min',
    difficulty: 'Easy',
    tags: ['Breakfast', 'High Carb', 'Quick'],
    suitableFor: ['general-health', 'maintain', 'weight-loss'],
    ingredients: ['Oats', 'Milk', 'Apple', 'Cinnamon', 'Walnuts'],
    instructions: ['Cook oats with milk', 'Top with diced apple and walnuts', 'Sprinkle cinnamon and serve warm'],
  },
  {
    id: '13',
    name: 'Egg Fried Rice Lite',
    image: 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&h=300&fit=crop',
    calories: 420,
    protein: 22,
    carbs: 58,
    fat: 10,
    prepTime: '16 min',
    difficulty: 'Easy',
    tags: ['Quick', 'Balanced', 'Budget'],
    suitableFor: ['maintain', 'general-health', 'muscle-gain'],
    ingredients: ['Cooked rice', 'Eggs', 'Peas', 'Carrots', 'Spring onion', 'Low-sodium soy sauce'],
    instructions: ['Scramble eggs in wok', 'Add vegetables and rice', 'Season and stir-fry until hot'],
  },
  {
    id: '14',
    name: 'Tofu Peanut Noodle Bowl',
    image: 'https://images.unsplash.com/photo-1498654896293-37aacf113fd9?w=400&h=300&fit=crop',
    calories: 500,
    protein: 24,
    carbs: 61,
    fat: 18,
    prepTime: '22 min',
    difficulty: 'Medium',
    tags: ['Vegetarian', 'High Carb', 'Meal Prep'],
    suitableFor: ['maintain', 'muscle-gain', 'general-health'],
    ingredients: ['Firm tofu', 'Rice noodles', 'Peanut butter', 'Lime', 'Cabbage', 'Carrot'],
    instructions: ['Pan-sear tofu cubes', 'Cook noodles and whisk sauce', 'Toss with vegetables and tofu'],
  },
  {
    id: '15',
    name: 'Baked Sweet Potato & Beans',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop',
    calories: 390,
    protein: 17,
    carbs: 58,
    fat: 9,
    prepTime: '35 min',
    difficulty: 'Easy',
    tags: ['Vegan', 'Fiber Rich', 'Budget'],
    suitableFor: ['weight-loss', 'general-health', 'maintain'],
    ingredients: ['Sweet potato', 'Black beans', 'Corn', 'Salsa', 'Greek yogurt'],
    instructions: ['Bake sweet potato until tender', 'Heat beans and corn', 'Stuff and top with salsa and yogurt'],
  },
  {
    id: '16',
    name: 'Chicken Pasta Primavera',
    image: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=400&h=300&fit=crop',
    calories: 540,
    protein: 39,
    carbs: 62,
    fat: 14,
    prepTime: '27 min',
    difficulty: 'Medium',
    tags: ['High Protein', 'Family Meal', 'Dinner'],
    suitableFor: ['muscle-gain', 'maintain'],
    ingredients: ['Chicken breast', 'Pasta', 'Zucchini', 'Bell pepper', 'Parmesan', 'Olive oil'],
    instructions: ['Cook pasta al dente', 'Saute chicken and vegetables', 'Combine and finish with parmesan'],
  },
  {
    id: '17',
    name: 'Berry Yogurt Overnight Oats',
    image: 'https://images.unsplash.com/photo-1495214783159-3503fd1b572d?w=400&h=300&fit=crop',
    calories: 310,
    protein: 20,
    carbs: 42,
    fat: 7,
    prepTime: '8 min',
    difficulty: 'Easy',
    tags: ['Breakfast', 'No Cook', 'High Protein'],
    suitableFor: ['weight-loss', 'general-health', 'muscle-gain'],
    ingredients: ['Rolled oats', 'Greek yogurt', 'Milk', 'Mixed berries', 'Chia seeds'],
    instructions: ['Mix oats, yogurt, and milk', 'Refrigerate overnight', 'Top with berries before eating'],
  },
  {
    id: '18',
    name: 'Steak & Veggie Sheet Pan',
    image: 'https://images.unsplash.com/photo-1559847844-5315695dadae?w=400&h=300&fit=crop',
    calories: 560,
    protein: 44,
    carbs: 26,
    fat: 30,
    prepTime: '30 min',
    difficulty: 'Medium',
    tags: ['High Protein', 'Low Carb', 'Dinner'],
    suitableFor: ['muscle-gain', 'general-health'],
    ingredients: ['Lean steak', 'Broccoli', 'Carrots', 'Potato wedges', 'Garlic', 'Rosemary'],
    instructions: ['Season steak and vegetables', 'Roast vegetables first', 'Sear steak and finish in oven', 'Serve sliced with roasted vegetables'],
  },
];